const examRecords = [
  {
    "record_id": "REC001",
    "exam_date": "2026-05-15",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-16",
    "student_id": "STU108",
    "subject": "Computer Science",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC002",
    "exam_date": "2026-07-09",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-03",
    "student_id": "STU101",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC003",
    "exam_date": "2026-07-17",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-35",
    "student_id": "STU114",
    "subject": "Computer Science",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC004",
    "exam_date": "2026-05-01",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-22",
    "student_id": "STU109",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC005",
    "exam_date": "2026-06-13",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-25",
    "student_id": "STU104",
    "subject": "Physics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC006",
    "exam_date": "2026-05-06",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-25",
    "student_id": "STU103",
    "subject": "Biology",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC007",
    "exam_date": "2026-07-19",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-05",
    "student_id": "STU102",
    "subject": "Computer Science",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC008",
    "exam_date": "2026-05-30",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-18",
    "student_id": "STU115",
    "subject": "Physics",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC009",
    "exam_date": "2026-05-27",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-39",
    "student_id": "STU106",
    "subject": "Biology",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC010",
    "exam_date": "2026-06-29",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-36",
    "student_id": "STU108",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC011",
    "exam_date": "2026-05-05",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-18",
    "student_id": "STU103",
    "subject": "Computer Science",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC012",
    "exam_date": "2026-06-10",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-26",
    "student_id": "STU115",
    "subject": "Computer Science",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC013",
    "exam_date": "2026-07-11",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-38",
    "student_id": "STU113",
    "subject": "Physics",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC014",
    "exam_date": "2026-05-18",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-04",
    "student_id": "STU104",
    "subject": "Computer Science",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC015",
    "exam_date": "2026-06-24",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-25",
    "student_id": "STU120",
    "subject": "Chemistry",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC016",
    "exam_date": "2026-07-10",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-35",
    "student_id": "STU109",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC017",
    "exam_date": "2026-05-21",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-17",
    "student_id": "STU117",
    "subject": "Computer Science",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC018",
    "exam_date": "2026-07-20",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-10",
    "student_id": "STU112",
    "subject": "Computer Science",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC019",
    "exam_date": "2026-07-07",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-32",
    "student_id": "STU101",
    "subject": "Mathematics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC020",
    "exam_date": "2026-06-09",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-16",
    "student_id": "STU119",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC021",
    "exam_date": "2026-05-09",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-31",
    "student_id": "STU118",
    "subject": "Computer Science",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC022",
    "exam_date": "2026-07-17",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-35",
    "student_id": "STU107",
    "subject": "Physics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC023",
    "exam_date": "2026-06-17",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-08",
    "student_id": "STU108",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC024",
    "exam_date": "2026-07-15",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-01",
    "student_id": "STU103",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC025",
    "exam_date": "2026-05-05",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-33",
    "student_id": "STU108",
    "subject": "Physics",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC026",
    "exam_date": "2026-07-09",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-16",
    "student_id": "STU116",
    "subject": "Chemistry",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC027",
    "exam_date": "2026-06-25",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-27",
    "student_id": "STU115",
    "subject": "Mathematics",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC028",
    "exam_date": "2026-05-13",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-22",
    "student_id": "STU104",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC029",
    "exam_date": "2026-06-27",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-12",
    "student_id": "STU109",
    "subject": "Chemistry",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC030",
    "exam_date": "2026-05-10",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-04",
    "student_id": "STU118",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC031",
    "exam_date": "2026-05-31",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-32",
    "student_id": "STU116",
    "subject": "Computer Science",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC032",
    "exam_date": "2026-05-22",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-25",
    "student_id": "STU109",
    "subject": "Chemistry",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC033",
    "exam_date": "2026-07-11",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-13",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC034",
    "exam_date": "2026-07-09",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-04",
    "student_id": "STU102",
    "subject": "Biology",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC035",
    "exam_date": "2026-07-07",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-33",
    "student_id": "STU103",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC036",
    "exam_date": "2026-05-31",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-37",
    "student_id": "STU108",
    "subject": "Biology",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC037",
    "exam_date": "2026-05-11",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-17",
    "student_id": "STU107",
    "subject": "Physics",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC038",
    "exam_date": "2026-05-17",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-21",
    "student_id": "STU103",
    "subject": "Mathematics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC039",
    "exam_date": "2026-07-12",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-35",
    "student_id": "STU107",
    "subject": "Biology",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC040",
    "exam_date": "2026-06-14",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-24",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC041",
    "exam_date": "2026-06-08",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-07",
    "student_id": "STU105",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC042",
    "exam_date": "2026-07-10",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-19",
    "student_id": "STU120",
    "subject": "Computer Science",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC043",
    "exam_date": "2026-06-03",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-04",
    "student_id": "STU103",
    "subject": "Chemistry",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC044",
    "exam_date": "2026-06-12",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-11",
    "student_id": "STU115",
    "subject": "Biology",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC045",
    "exam_date": "2026-05-02",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-10",
    "student_id": "STU118",
    "subject": "Mathematics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC046",
    "exam_date": "2026-05-19",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-03",
    "student_id": "STU110",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC047",
    "exam_date": "2026-05-27",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-23",
    "student_id": "STU118",
    "subject": "Chemistry",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC048",
    "exam_date": "2026-05-31",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-27",
    "student_id": "STU101",
    "subject": "Computer Science",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC049",
    "exam_date": "2026-06-22",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-11",
    "student_id": "STU104",
    "subject": "Chemistry",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC050",
    "exam_date": "2026-05-29",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-23",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC051",
    "exam_date": "2026-05-25",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-18",
    "student_id": "STU103",
    "subject": "Physics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC052",
    "exam_date": "2026-06-21",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-08",
    "student_id": "STU109",
    "subject": "Computer Science",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC053",
    "exam_date": "2026-06-03",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-39",
    "student_id": "STU114",
    "subject": "Physics",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC054",
    "exam_date": "2026-06-25",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-37",
    "student_id": "STU107",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC055",
    "exam_date": "2026-05-01",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-28",
    "student_id": "STU103",
    "subject": "Physics",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC056",
    "exam_date": "2026-05-16",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-27",
    "student_id": "STU111",
    "subject": "Chemistry",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC057",
    "exam_date": "2026-05-17",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-25",
    "student_id": "STU106",
    "subject": "Biology",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC058",
    "exam_date": "2026-07-10",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-19",
    "student_id": "STU107",
    "subject": "Chemistry",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC059",
    "exam_date": "2026-06-11",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-29",
    "student_id": "STU107",
    "subject": "Biology",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC060",
    "exam_date": "2026-05-22",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-33",
    "student_id": "STU120",
    "subject": "Physics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC061",
    "exam_date": "2026-05-31",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-13",
    "student_id": "STU105",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC062",
    "exam_date": "2026-06-30",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-27",
    "student_id": "STU119",
    "subject": "Computer Science",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC063",
    "exam_date": "2026-07-03",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-10",
    "student_id": "STU101",
    "subject": "Mathematics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC064",
    "exam_date": "2026-07-06",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-36",
    "student_id": "STU108",
    "subject": "Mathematics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC065",
    "exam_date": "2026-06-29",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-40",
    "student_id": "STU117",
    "subject": "Chemistry",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC066",
    "exam_date": "2026-05-21",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-17",
    "student_id": "STU108",
    "subject": "Physics",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC067",
    "exam_date": "2026-05-31",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-05",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC068",
    "exam_date": "2026-07-09",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-10",
    "student_id": "STU108",
    "subject": "Chemistry",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC069",
    "exam_date": "2026-05-28",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-27",
    "student_id": "STU111",
    "subject": "Biology",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC070",
    "exam_date": "2026-05-27",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-38",
    "student_id": "STU101",
    "subject": "Biology",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC071",
    "exam_date": "2026-06-15",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-27",
    "student_id": "STU118",
    "subject": "Biology",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC072",
    "exam_date": "2026-07-02",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-28",
    "student_id": "STU116",
    "subject": "Mathematics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC073",
    "exam_date": "2026-06-21",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-09",
    "student_id": "STU120",
    "subject": "Biology",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC074",
    "exam_date": "2026-07-15",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-28",
    "student_id": "STU105",
    "subject": "Chemistry",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC075",
    "exam_date": "2026-06-18",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-30",
    "student_id": "STU111",
    "subject": "Physics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC076",
    "exam_date": "2026-06-23",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-31",
    "student_id": "STU101",
    "subject": "Biology",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC077",
    "exam_date": "2026-06-14",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-03",
    "student_id": "STU101",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC078",
    "exam_date": "2026-07-19",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-09",
    "student_id": "STU116",
    "subject": "Mathematics",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC079",
    "exam_date": "2026-06-29",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-11",
    "student_id": "STU120",
    "subject": "Biology",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC080",
    "exam_date": "2026-05-21",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-38",
    "student_id": "STU101",
    "subject": "Physics",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC081",
    "exam_date": "2026-06-18",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "B-05",
    "student_id": "STU119",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC082",
    "exam_date": "2026-06-08",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-23",
    "student_id": "STU118",
    "subject": "Chemistry",
    "invigilator": "Prof. Charles Xavier",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC083",
    "exam_date": "2026-07-04",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-27",
    "student_id": "STU116",
    "subject": "Mathematics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC084",
    "exam_date": "2026-06-28",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-12",
    "student_id": "STU117",
    "subject": "Physics",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC085",
    "exam_date": "2026-07-08",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-28",
    "student_id": "STU119",
    "subject": "Physics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC086",
    "exam_date": "2026-05-12",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-16",
    "student_id": "STU115",
    "subject": "Biology",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC087",
    "exam_date": "2026-06-13",
    "session": "Morning",
    "hall": "Gymnasium",
    "seat_no": "G-21",
    "student_id": "STU106",
    "subject": "Chemistry",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC088",
    "exam_date": "2026-06-03",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-39",
    "student_id": "STU109",
    "subject": "Biology",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC089",
    "exam_date": "2026-05-25",
    "session": "Morning",
    "hall": "Hall B",
    "seat_no": "B-27",
    "student_id": "STU116",
    "subject": "Biology",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC090",
    "exam_date": "2026-07-02",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-06",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC091",
    "exam_date": "2026-06-09",
    "session": "Afternoon",
    "hall": "Gymnasium",
    "seat_no": "G-36",
    "student_id": "STU117",
    "subject": "Physics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC092",
    "exam_date": "2026-07-10",
    "session": "Afternoon",
    "hall": "Hall C",
    "seat_no": "C-30",
    "student_id": "STU109",
    "subject": "Physics",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC093",
    "exam_date": "2026-05-25",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-35",
    "student_id": "STU106",
    "subject": "Computer Science",
    "invigilator": "Dr. Ashwani Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC094",
    "exam_date": "2026-06-05",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-13",
    "student_id": "STU110",
    "subject": "Computer Science",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC095",
    "exam_date": "2026-05-02",
    "session": "Morning",
    "hall": "Hall C",
    "seat_no": "C-03",
    "student_id": "STU102",
    "subject": "Biology",
    "invigilator": "Dr. Robert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC096",
    "exam_date": "2026-05-17",
    "session": "Afternoon",
    "hall": "Hall A",
    "seat_no": "A-01",
    "student_id": "STU119",
    "subject": "Physics",
    "invigilator": "Dr. Rupert Smith",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC097",
    "exam_date": "2026-06-13",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-17",
    "student_id": "STU116",
    "subject": "Mathematics",
    "invigilator": "Dr. Ashwini Sekar",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC098",
    "exam_date": "2026-06-15",
    "session": "Morning",
    "hall": "Hall A",
    "seat_no": "A-15",
    "student_id": "STU112",
    "subject": "Chemistry",
    "invigilator": "",
    "student_attendance": "Present"
  },
  {
    "record_id": "REC099",
    "exam_date": "2026-06-16",
    "session": "Afternoon",
    "hall": "Hall B",
    "seat_no": "",
    "student_id": "STU114",
    "subject": "Biology",
    "invigilator": "Dr. Jane Doe",
    "student_attendance": "Absent"
  },
  {
    "record_id": "REC100",
    "exam_date": "2026-12-25",
    "session": "Morning",
    "hall": "Storage Room C",
    "seat_no": "Z-99",
    "student_id": "STU999",
    "subject": "Astrology",
    "invigilator": "Dr. Orphan",
    "student_attendance": "Absent"
  }
];
